modernize travis setup

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,81 +1,99 @@
-language: generic
+language: node_js
 
-matrix:
-  include:
-# Coverage
-  - os: osx
-    compiler: clang
-    env: NODE_VERSION=0.10 COVERAGE=true CXXFLAGS="--coverage" LDFLAGS="--coverage"
-# Linux
-  - os: linux
-    compiler: clang
-    env: CXX=clang++-3.5 NODE_VERSION=6
-    sudo: false
-  - os: linux
-    compiler: clang
-    env: CXX=clang++-3.5 NODE_VERSION=4
-    sudo: false
-  - os: linux
-    compiler: clang
-    env: CXX=clang++-3.5 NODE_VERSION=0.12
-    sudo: false
-  - os: linux
-    compiler: clang
-    env: CXX=clang++-3.5 NODE_VERSION=0.10
-    sudo: false
-# OS X
-  - os: osx
-    osx_image: xcode7
-    compiler: clang
-    env: NODE_VERSION=6
-  - os: osx
-    osx_image: xcode7
-    compiler: clang
-    env: NODE_VERSION=4
-  - os: osx
-    osx_image: xcode7
-    compiler: clang
-    env: NODE_VERSION=0.12
-  - os: osx
-    osx_image: xcode7
-    compiler: clang
-    env: NODE_VERSION=0.10
+sudo: false
 
-addons:
-  apt:
-    sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5' ]
-    packages: [ 'clang-3.5', 'libstdc++-4.9-dev', 'libstdc++6' ]
-
+# build options and AWS keys for publishing binaries
+# note: you'll need to generate your own keys for publishing a separate project
 env:
   global:
-  - secure: "XV0lekmfgT+D9t0ZTIU+UJF6g+p3cBQMO6T6C9lkoKTC0YbtLtxSFtBahD/4PjL86DMJgTaf1nBmxqOxbrfkcpJUxnLe3r8u4Z2L/+7+QSACLNktlIfWNSO+33WxKNb4mVw6jMFZIo4ZurF016MXYzLzjpxRELW2oO2STUs2m44="
-  - secure: "CQNHbxw8yHlAdUVbKokHzHmj7C+duXP3mifWOkZm9GKw4myWsRFhhoSYZmOSkgj9EWfYYkedrqEr9+GaMg9rkVJuO/7jzn6S+M7CFXKJju6MoZEDO6WcFva4M8pw6IFb9q22GcQ+OsE8/i0DwchTokyFkNb3fpwWuwROUPQ/nWg="
+    - secure: XV0lekmfgT+D9t0ZTIU+UJF6g+p3cBQMO6T6C9lkoKTC0YbtLtxSFtBahD/4PjL86DMJgTaf1nBmxqOxbrfkcpJUxnLe3r8u4Z2L/+7+QSACLNktlIfWNSO+33WxKNb4mVw6jMFZIo4ZurF016MXYzLzjpxRELW2oO2STUs2m44=
+    - secure: CQNHbxw8yHlAdUVbKokHzHmj7C+duXP3mifWOkZm9GKw4myWsRFhhoSYZmOSkgj9EWfYYkedrqEr9+GaMg9rkVJuO/7jzn6S+M7CFXKJju6MoZEDO6WcFva4M8pw6IFb9q22GcQ+OsE8/i0DwchTokyFkNb3fpwWuwROUPQ/nWg=
 
-before_install:
-- export COVERAGE=${COVERAGE:-false}
-- export PYTHONUSERBASE=$(pwd)/.local
-- mkdir -p ${PYTHONUSERBASE}
-- if [[ ${COVERAGE} == true ]]; then
-     if [[ $(uname -s) == 'Linux' ]]; then
-        pip install --user cpp-coveralls;
-     else
-        easy_install --user cpp-coveralls;
-     fi;
-  fi;
-- source ./scripts/install_node.sh ${NODE_VERSION}
+# enable c++11/14 builds
+addons:
+  apt:
+    sources: [ 'ubuntu-toolchain-r-test' ]
+    packages: [ 'libstdc++-4.9-dev' ]
 
 install:
-- ./scripts/install.sh
+  # set up the environment by installing mason and clang++
+  - ./scripts/setup.sh --config local.env
+  # put mason and clang++ on PATH
+  - source local.env
+  - node -v
+  - which node
+  - clang++ -v
+  - which clang++
+  - make ${BUILDTYPE}
 
-before_script:
-- ulimit -c unlimited -S
-- ulimit -a
-
+# run tests
 script:
-- ./scripts/test.sh
+  - npm test
+  # after successful tests, publish binaries if specified in commit message
+  - ./scripts/publish.sh --toolset=${TOOLSET:-} --debug=$([ "${BUILDTYPE}" == 'debug' ] && echo "true" || echo "false")
 
-after_success:
-- ./scripts/travis_publish.sh
-
-git:
-  submodules: true
+# the matrix allows you to specify different operating systems and environments to 
+# run your tests and build binaries
+matrix:
+  include:
+    # linux publishable node v4/release
+    - os: linux
+      env: BUILDTYPE=release
+      node_js: 4
+    # linux publishable node v4/debug
+    - os: linux
+      env: BUILDTYPE=debug
+      node_js: 4
+    # linux publishable node v6
+    - os: linux
+      env: BUILDTYPE=release
+      node_js: 6
+    # linux publishable node v6/debug
+    - os: linux
+      env: BUILDTYPE=debug
+      node_js: 6
+    # osx publishable node v4
+    - os: osx
+      osx_image: xcode8.2
+      env: BUILDTYPE=release
+      node_js: 4
+    # osx publishable node v6
+    - os: osx
+      osx_image: xcode8.2
+      env: BUILDTYPE=release
+      node_js: 6
+    # Sanitizer build node v4/Debug
+    - os: linux
+      env: BUILDTYPE=debug TOOLSET=asan
+      node_js: 4
+      # Overrides `install` to set up custom asan flags
+      install:
+        - ./scripts/setup.sh --config local.env
+        # put mason and clang++ on PATH
+        - source local.env
+        # Note: to build without stopping on errors remove the -fno-sanitize-recover=all flag
+        # You might want to do this if there are multiple errors and you want to see them all before fixing
+        - export CXXFLAGS="${MASON_SANITIZE_CXXFLAGS} -fno-sanitize-recover=all"
+        - export LDFLAGS="${MASON_SANITIZE_LDFLAGS}"
+        - make ${BUILDTYPE}
+      # Overrides `script` to disable asan LD_PRELOAD before publishing
+      script:
+        - export LD_PRELOAD=${MASON_LLVM_RT_PRELOAD}
+        - export ASAN_OPTIONS=fast_unwind_on_malloc=0:${ASAN_OPTIONS}
+        - npm test
+        - unset LD_PRELOAD
+        # after successful tests, publish binaries if specified in commit message
+        - ./scripts/publish.sh --toolset=${TOOLSET:-} --debug=$([ "${BUILDTYPE}" == 'debug' ] && echo "true" || echo "false")
+    # Coverage build
+    - os: linux
+      env: BUILDTYPE=debug CXXFLAGS="--coverage" LDFLAGS="--coverage"
+      node_js: 4
+      # Overrides `script` to publish coverage data to codecov
+      script:
+        - npm test
+        - mason install llvm-cov ${MASON_LLVM_RELEASE}
+        - mason link llvm-cov ${MASON_LLVM_RELEASE}
+        - which llvm-cov
+        - curl -S -f https://codecov.io/bash -o codecov
+        - chmod +x codecov
+        - ./codecov -x "llvm-cov gcov" -Z
